package com.hms.constants;

public enum TableName {
	inv_vendor_master,
	inv_uom_master,
	inv_category_master,
	inv_shelf_master,
	inv_form_master,
	inv_trolley_master,
	inv_manufacturer_master,
	inv_warehouse_master,
	inv_ingredient_master,
	inv_med_template_master,
	inv_packing_master,
	inv_product_master,
	inv_grn_stock_adj_master,
	inv_gin_stock_adj_master,
	inv_requirement,
	inv_document_master,
	inv_taxsetup_master,
	inv_financial_year,
	inv_document_numbering_master,
	inv_item_master,
	inv_item_sale,
	inv_item_warehouse,
	inv_item_other_info,
	inv_item_purchase,
	inv_party_master,
	inv_party_master_general_info,
	inv_party_master_contact_info,
	inv_party_master_payment_info,
	inv_party_master_other_info,
	inv_party_master_address_info,

 	inv_mrn_master,
 	inv_mrn_item_info_slave,
 	inv_item_party_details,
 	inv_sub_contracting_material_issue_master,
 	
 	inv_purchase_common_master,
 	inv_batch_stock,
 	inv_batch_stock_master,
 	inv_subinventory_master, 
 	inv_new_purchase_order_master, 
 	inv_purchase_order_item_master, 
 	inv_purchase_invoice_master, 
 	inv_purchase_invoice_item_master, inv_purchase_return_master, 

 	inv_purchase_return_item_master,
 	maintainance_machine,
 	inv_consumption_master,
 	inv_consumption_item_info_slave, 
 	inv_purchase_invoice_mode_of_payment,
 	radiation_master,
	nursing_notes, inv_abcanalysis_details,
	inv_subinventory_stock_master, inv_charges_master,inv_hospital_details,inv_termsandcondition_master,inv_opening_stock_master,inv_closing_stock_master,
	inv_new_purchase_order_master2,inv_purchase_common_master2,inv_purchase_order_item_master2,inv_purchase_order_terms_and_condition_master2,
	inv_purchase_qtn_enquiry_master, inv_purchase_qtn_enquiry_item_master, inv_item_partycontrct_details, inv_stock_trnsfer_to_center,inv_mrn_master_lnl,inv_mrn_master_cssd,inv_laundry_master,inv_cssd_master; 
}