package com.hms.dto;

import java.util.List;

import org.codehaus.jackson.annotate.JsonGetter;
import org.codehaus.jackson.annotate.JsonSetter;

/**
 * OperationDocTbl generated by hbm2java
 */
public class OperationDocTbl implements java.io.Serializable {

	private Integer idoperationDocTbl;
	private Integer idtreatmentOperationManage;
	private Integer docId;
	private String status;
	private String docType;
	private String docName;
	private String surgeonType;
	private String remove;
	private String confirm;
	private String confirmTime;
	private String arrival;
	private String arrivalTime;
	private String absent;
	private String narration;
	
	@JsonGetter("idtremng")
	public Integer getIdtreatmentOperationManage() {
		return idtreatmentOperationManage;
	}
	@JsonSetter("idtremng")
	public void setIdtreatmentOperationManage(Integer idtreatmentOperationManage) {
		this.idtreatmentOperationManage = idtreatmentOperationManage;
	}
	@JsonGetter("remove")
	public String getRemove() {
		return remove;
	}
	@JsonSetter("remove")
	public void setRemove(String remove) {
		this.remove = remove;
	}
	@JsonGetter("confirm")
	public String getConfirm() {
		return confirm;
	}
	@JsonSetter("confirm")
	public void setConfirm(String confirm) {
		this.confirm = confirm;
	}
	@JsonGetter("conTime")
	public String getConfirmTime() {
		return confirmTime;
	}
	@JsonSetter("conTime")
	public void setConfirmTime(String confirmTime) {
		this.confirmTime = confirmTime;
	}
	@JsonGetter("arrival")
	public String getArrival() {
		return arrival;
	}

	@JsonSetter("arrival")
	public void setArrival(String arrival) {
		this.arrival = arrival;
	}
	@JsonGetter("arrTime")
	public String getArrivalTime() {
		return arrivalTime;
	}
	@JsonSetter("arrTime")
	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime;
	}
	
	private List<OperationDocTbl> listOpertationDoc;
	private Doctor objDoc;
	private Doctor objDoctor;

	@JsonGetter("doctp")
	public String getDocType() {
		return docType;
	}

	@JsonSetter("doctp")
	public void setDocType(String docType) {
		this.docType = docType;
	}

	@JsonGetter("idopDocTbl")
	public Integer getIdoperationDocTbl() {
		return this.idoperationDocTbl;
	}

	@JsonSetter("idopDocTbl")
	public void setIdoperationDocTbl(Integer idoperationDocTbl) {
		this.idoperationDocTbl = idoperationDocTbl;
	}

	@JsonGetter("idopDoc")
	public Integer getDocId() {
		return this.docId;
	}

	@JsonSetter("idopDoc")
	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@JsonGetter("st")
	public String getStatus() {
		return this.status;
	}

	@JsonSetter("st")
	public void setStatus(String status) {
		this.status = status;
	}

	@JsonGetter("liopDoc")
	public List<OperationDocTbl> getListOpertationDoc() {
		return listOpertationDoc;
	}

	@JsonSetter("liopDoc")
	public void setListOpertationDoc(List<OperationDocTbl> listOpertationDoc) {
		this.listOpertationDoc = listOpertationDoc;
	}

	@JsonGetter("docName")
	public String getDocName() {
		return docName;
	}

	@JsonSetter("docName")
	public void setDocName(String docName) {
		this.docName = docName;
	}
	@JsonGetter("surgtp")
	public String getSurgeonType() {
		return surgeonType;
	}
	@JsonSetter("surgtp")
	public void setSurgeonType(String surgeonType) {
		this.surgeonType = surgeonType;
	}

	public Doctor getObjDoc() {
		return objDoc;
	}

	public void setObjDoc(Doctor objDoc) {
		this.objDoc = objDoc;
	}
	@JsonGetter("absent")
	public String getAbsent() {
		return absent;
	}
	@JsonSetter("absent")
	public void setAbsent(String absent) {
		this.absent = absent;
	}
	@JsonGetter("narra")
	public String getNarration() {
		return narration;
	}
	@JsonSetter("narra")
	public void setNarration(String narration) {
		this.narration = narration;
	}
	
		@JsonSetter("obd")
	public void setObjDoctor(Doctor objDoctor) {
		this.objDoctor = objDoctor;
	}

	@JsonGetter("obd")
	public Doctor getObjDoctor() {
		return objDoctor;
	}


}
